blank_issues_enabled: false
contact_links:
  - name: mLLMCelltype Documentation
    url: https://github.com/cafferychen777/mLLMCelltype#readme
    about: Check the mLLMCelltype documentation
  - name: GitHub Discussions
    url: https://github.com/cafferychen777/mLLMCelltype/discussions
    about: Ask questions or discuss ideas
  - name: mLLMCelltype 文档
    url: https://github.com/cafferychen777/mLLMCelltype#readme
    about: 查看mLLMCelltype文档
  - name: GitHub 讨论
    url: https://github.com/cafferychen777/mLLMCelltype/discussions
    about: 提问或讨论想法