on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown

permissions:
  contents: write

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglpk-dev libcurl4-openssl-dev libssl-dev libxml2-dev libfontconfig1-dev libfreetype6-dev libfribidi-dev libharfbuzz-dev libpng-dev libtiff5-dev libcairo2-dev libxt-dev

      - name: Install required packages
        run: |
          install.packages(c("pkgdown", "knitr", "rmarkdown", "devtools", "systemfonts", "ragg", "textshaping", "svglite", "ggplot2", "patchwork", "viridis", "ggExtra"))
        shell: Rscript {0}

      - name: Install package dependencies
        run: |
          setwd("R")
          devtools::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Verify systemfonts installation
        run: |
          Rscript -e "packageVersion('systemfonts')"
          Rscript -e "packageVersion('ragg')"
          Rscript -e "packageVersion('textshaping')"

      - name: Build site
        run: |
          setwd("R")
          pkgdown::build_site()
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: R/docs
          clean: true
